export const types = {
    LOAD_POST_START : "LOAD_POST_START",
    LOAD_POST_SUCCESS : "LOAD_POST_SUCCESS",
    LOAD_POST_FAIL: "LOAD_POST_FAIL",
    ADD_PRODUCT: "ADD_PRODUCT",
    ADD_PRODUCT_FAIL: "ADD_PRODUCT_FAIL",
    DELETE_PRODUCT: "DELETE_PRODUCT"
};
